const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const copy={
  zh:{navMeasure:'量測',navResults:'分析',navRuns:'紀錄',navCalibration:'校正',navGuide:'系統',serverState:'SERVER',measureHeading:'量測',measureIntro:'建立單點或掃描條件，執行前由安全摘要再次確認。',analyzeHelp:'切換指標、查看逐點資料，或從量測紀錄加入多筆 Run 比較。',metric:'指標',instrument:'儀器',planTitle:'量測設定',planHelp:'選擇量測類型並輸入參數。',single:'單點',frequencySweep:'頻率掃描',powerSweep:'功率掃描',centerFrequency:'中心頻率',bandwidth:'頻寬',startFrequency:'起始頻率',stopFrequency:'結束頻率',frequencyStep:'頻率步進',startPower:'起始功率',stopPower:'結束功率',powerStep:'功率步進',generatorPower:'Generator 功率',dwell:'停留時間',testName:'測試名稱',reviewTitle:'執行摘要',reviewHelp:'送出前確認點位與限制。',mode:'模式',points:'點數',estimatedTime:'預估時間',maximumPower:'最大功率',demoSafe:'Demo 安全',demoSafeHelp:'不會連線儀器或產生 RF。',runDemo:'執行 Demo 量測',beforeRun:'執行前',checkMode:'確認右上角為 DEMO',checkValues:'檢查頻率、功率與點數',openResults:'完成後前往分析頁',resultsTitle:'分析與比較',noResults:'尚無量測結果',noResultsHelp:'執行 Demo 量測或從紀錄選取 Run，圖表與逐點資料會顯示在這裡。',runsTitle:'量測紀錄',refresh:'重新整理',calibrationTitle:'校正流程重新設計中',calibrationHelp:'新版將使用四步精靈：器材、讀值、線損檢查、核准。',guideTitle:'系統與快速開始',startDemo:'啟動 Demo',copy:'複製指令',rfHold:'RF 暫停',rfHoldHelp:'供電不穩定期間請使用 --demo-only。'},
  en:{navMeasure:'Measure',navResults:'Analyze',navRuns:'Runs',navCalibration:'Calibration',navGuide:'System',serverState:'SERVER',measureHeading:'Measure',measureIntro:'Build a single-point or sweep plan and review the safety summary before execution.',analyzeHelp:'Switch metrics, inspect point data, or compare selected runs from history.',metric:'Metric',instrument:'Instrument',planTitle:'Measurement settings',planHelp:'Choose a measurement type and enter parameters.',single:'Single',frequencySweep:'Frequency sweep',powerSweep:'Power sweep',centerFrequency:'Center frequency',bandwidth:'Bandwidth',startFrequency:'Start frequency',stopFrequency:'Stop frequency',frequencyStep:'Frequency step',startPower:'Start power',stopPower:'Stop power',powerStep:'Power step',generatorPower:'Generator power',dwell:'Dwell time',testName:'Test name',reviewTitle:'Execution summary',reviewHelp:'Review points and limits before running.',mode:'Mode',points:'Points',estimatedTime:'Estimated time',maximumPower:'Maximum power',demoSafe:'Demo safe',demoSafeHelp:'No instrument connection or RF.',runDemo:'Run Demo measurement',beforeRun:'Before running',checkMode:'Confirm the top-right badge says DEMO',checkValues:'Review frequency, power, and points',openResults:'Open Analyze when complete',resultsTitle:'Analyze & compare',noResults:'No measurement results',noResultsHelp:'Run a Demo measurement or select runs from history to display plots and point data.',runsTitle:'Run history',refresh:'Refresh',calibrationTitle:'Calibration workflow is being rebuilt',calibrationHelp:'V2 will use a four-step wizard: equipment, readings, loss review, and approval.',guideTitle:'System & quick start',startDemo:'Start Demo',copy:'Copy command',rfHold:'RF on hold',rfHoldHelp:'Use --demo-only while instrument power is unstable.'}
};
Object.assign(copy.zh,{completedAt:'完成時間',outputLocation:'輸出位置',runsHelp:'查看時間、輸出位置與檔案；刪除會移至可復原的 Trash。',technicalDetails:'技術詳細資料',openFolder:'開啟資料夾',deleteRun:'刪除紀錄',deleteConfirmTitle:'確認移至 Trash',cancel:'取消',moveToTrash:'移至 Trash'});
Object.assign(copy.en,{completedAt:'Completed at',outputLocation:'Output location',runsHelp:'Review timestamps, output locations, and files. Delete moves a run to recoverable Trash.',technicalDetails:'Technical details',openFolder:'Open folder',deleteRun:'Delete run',deleteConfirmTitle:'Confirm move to Trash',cancel:'Cancel',moveToTrash:'Move to Trash'});
let language='zh',axis='single',activeJob=null,allRuns=[],traces=[],selectedRunKeys=new Set();
function t(key){return copy[language][key]||key}
function applyLanguage(){document.documentElement.lang=language==='zh'?'zh-Hant':'en';$$('[data-t]').forEach(node=>node.textContent=t(node.dataset.t));$('#languageButton').textContent=language==='zh'?'EN':'中文';updateSummary()}
$('#languageButton').onclick=()=>{language=language==='zh'?'en':'zh';applyLanguage()};
const themeOrder=['dark','light','system'];
function applyTheme(value){const resolved=value==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):value;document.documentElement.dataset.theme=resolved;$('#themeButton').textContent=value==='dark'?'☾':value==='light'?'☀':'◐';$('#themeButton').title=`Theme: ${value}`;localStorage.setItem('cmp180-theme',value)}
$('#themeButton').onclick=()=>{const current=localStorage.getItem('cmp180-theme')||'dark';applyTheme(themeOrder[(themeOrder.indexOf(current)+1)%themeOrder.length])};

function showView(id){$$('.nav-item,.view').forEach(node=>node.classList.remove('active'));$(`[data-view="${id}"]`).classList.add('active');$(`#${id}`).classList.add('active');if(id==='runs')loadRuns()}
$$('.nav-item').forEach(button=>button.onclick=()=>showView(button.dataset.view));

function setAxis(next){axis=next;$$('[data-axis]').forEach(button=>button.classList.toggle('active',button.dataset.axis===axis));$$('.field[class*="axis-"]').forEach(field=>{field.hidden=!field.classList.contains(`axis-${axis}`)});updateSummary()}
$$('[data-axis]').forEach(button=>button.onclick=()=>setAxis(button.dataset.axis));
$('#planForm').addEventListener('input',updateSummary);

function number(name){return Number(new FormData($('#planForm')).get(name))}
function planSummary(){
  // 前端摘要只提供即時回饋；後端仍會再次驗證點數與 -40 dBm 安全上限，不能只信任瀏覽器。
  if(axis==='single')return{points:1,power:number('power_dbm'),seconds:.5,valid:number('power_dbm')<=-40};
  const start=axis==='frequency'?number('start_mhz'):number('start_dbm');
  const stop=axis==='frequency'?number('stop_mhz'):number('stop_dbm');
  const step=axis==='frequency'?number('step_mhz'):number('step_dbm');
  const points=step>0&&stop>=start?Math.floor((stop-start)/step)+1:0;
  const power=axis==='frequency'?number('power_dbm'):stop;
  return{points,power,seconds:Math.max(points,1)*number('dwell_ms')/1000,valid:points>0&&points<=11&&power<=-40};
}
function updateSummary(){const summary=planSummary();$('#summaryMode').textContent=`Demo · ${axis==='single'?t('single'):axis==='frequency'?t('frequencySweep'):t('powerSweep')}`;$('#summaryPoints').textContent=summary.points||'—';$('#summaryTime').textContent=summary.seconds<1?'< 1 s':`${summary.seconds.toFixed(1)} s`;$('#summaryPower').textContent=Number.isFinite(summary.power)?`${summary.power} dBm`:'—';const state=$('#safetyState');state.classList.toggle('safe',summary.valid);state.classList.toggle('error',!summary.valid);state.querySelector('span').textContent=summary.valid?'✓':'!';state.querySelector('strong').textContent=summary.valid?t('demoSafe'):(language==='zh'?'計畫不符合限制':'Plan is outside limits');state.querySelector('p').textContent=summary.valid?t('demoSafeHelp'):(language==='zh'?'最多 11 點且功率不得高於 -40 dBm。':'Maximum 11 points and no power above -40 dBm.');$('#runButton').disabled=!summary.valid||activeJob!==null}

function payload(){
  const form=new FormData($('#planForm'));
  // UI 使用工程師熟悉的 MHz；API 與儀器工作流程一律使用 Hz，避免單位混用造成錯頻。
  const common={bandwidth_hz:number('bandwidth_mhz')*1e6,test_name:form.get('test_name')};
  if(axis==='single')return{path:'/api/mock/single',body:{...common,frequency_hz:number('center_mhz')*1e6,generator_power_dbm:number('power_dbm')}};
  if(axis==='frequency')return{path:'/api/jobs/mock/frequency-sweep',body:{...common,start_hz:number('start_mhz')*1e6,stop_hz:number('stop_mhz')*1e6,step_hz:number('step_mhz')*1e6,generator_power_dbm:number('power_dbm'),dwell_ms:number('dwell_ms')}};
  return{path:'/api/jobs/mock/power-sweep',body:{...common,frequency_hz:number('center_mhz')*1e6,start_dbm:number('start_dbm'),stop_dbm:number('stop_dbm'),step_dbm:number('step_dbm'),dwell_ms:number('dwell_ms')}};
}
async function post(path,body){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data}
$('#runButton').onclick=async()=>{const request=payload();try{$('#runButton span').textContent=language==='zh'?'執行中…':'Running…';$('#runButton').disabled=true;if(axis==='single'){render(await post(request.path,request.body));return}const job=await post(request.path,request.body);activeJob=job.job_id;await pollJob()}catch(error){toast(error.message)}finally{activeJob=null;$('#runButton span').textContent=t('runDemo');updateSummary()}};
async function pollJob(){while(activeJob){const response=await fetch(`/api/jobs/${activeJob}`);const job=await response.json();$('#runButton span').textContent=`${job.completed_points}/${job.total_points}`;if(job.state==='complete'){render(job.result);return}if(job.state==='failed')throw new Error(job.error);await new Promise(resolve=>setTimeout(resolve,180))}}

function finite(values,key){return values.map(point=>point[key]).filter(Number.isFinite)}
function normalizeStoredPoints(results){const points=Array.isArray(results)?results:(results?.points||[]);const numeric=value=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:null};return points.map((point,index)=>({...point,point_index:Number.isFinite(Number(point.point_index))?Number(point.point_index):index,frequency_hz:numeric(point.frequency_hz),generator_power_dbm:numeric(point.generator_power_dbm),bandwidth_hz:numeric(point.bandwidth_hz),evm_all_db:numeric(point.evm_all_db??point.evm_all_carriers_db),evm_data_db:numeric(point.evm_data_db??point.evm_data_carriers_db),evm_pilot_db:numeric(point.evm_pilot_db??point.evm_pilot_carriers_db),burst_power_dbm:numeric(point.burst_power_dbm),frequency_error_hz:numeric(point.frequency_error_hz),clock_error_ppm:numeric(point.clock_error_ppm),limit_status:point.limit_status||(String(point.evm_all_carriers_db).toUpperCase()==='INV'?'INVALID':'UNASSESSED')}))}
function metric(label,value){return `<div class="metric"><small>${label}</small><strong>${value}</strong></div>`}
function render(data){const points=data.points||[];const evm=finite(points,'evm_all_db'),power=finite(points,'burst_power_dbm'),frequencyError=finite(points,'frequency_error_hz');const runId=data.artifacts?.run_id||data.run_id||'run';traces=[{id:runId,name:data.test_name||runId,color:'#27dce6',visible:true,points}];$('#emptyResults').hidden=true;$('#resultContent').hidden=false;$('#resultStatus').textContent=data.simulated?'DEMO DATA':'HARDWARE';$('#resultTimestamp').textContent=new Date(data.created_at||Date.now()).toLocaleString();$('#resultRunId').textContent=runId;$('#resultOutput').textContent=data.output_location||'—';$('#metrics').innerHTML=metric('POINTS',points.length)+metric('AVG EVM',evm.length?`${(evm.reduce((a,b)=>a+b,0)/evm.length).toFixed(2)} dB`:'—')+metric('AVG POWER',power.length?`${(power.reduce((a,b)=>a+b,0)/power.length).toFixed(2)} dBm`:'—')+metric('MAX |FERR|',frequencyError.length?`${Math.max(...frequencyError.map(Math.abs)).toFixed(1)} Hz`:'—');renderTraceList();renderPointTable(points);drawTraces();const urls=data.artifact_urls||{};$('#artifactLinks').innerHTML=Object.entries(urls).filter(([,url])=>url).map(([key,url])=>`<a href="${url}" target="_blank" rel="noopener">${key.toUpperCase()}</a>`).join('');showView('results')}
function renderPointTable(points){$('#pointRows').innerHTML=points.map(point=>`<tr><td>${point.point_index+1}</td><td>${(point.frequency_hz/1e6).toFixed(3)} MHz</td><td>${point.generator_power_dbm} dBm</td><td>${Number.isFinite(point.evm_all_db)?point.evm_all_db.toFixed(2):'INVALID'}</td><td>${Number.isFinite(point.burst_power_dbm)?point.burst_power_dbm.toFixed(2):'INVALID'}</td><td>${Number.isFinite(point.frequency_error_hz)?point.frequency_error_hz.toFixed(2):'INVALID'}</td><td class="status-${String(point.limit_status||'invalid').toLowerCase()}">${point.limit_status||'INVALID'}</td></tr>`).join('')}
function renderTraceList(){const list=$('#traceList');list.innerHTML=traces.map((trace,index)=>`<div class="trace-item" draggable="true" data-trace-index="${index}"><input type="checkbox" ${trace.visible?'checked':''} aria-label="Trace visible"><input type="color" value="${trace.color}" aria-label="Trace color"><input type="text" value="${escapeHtml(trace.name)}" aria-label="Trace name"></div>`).join('');$('#compareHint').textContent=traces.length>1?(language==='zh'?`${traces.length} 筆 Run；拖曳可調整圖例順序。`:`${traces.length} runs; drag to reorder legend.`):(language==='zh'?'EVM dB 越負通常越好。':'More-negative EVM dB is normally better.');$$('.trace-item').forEach(item=>{const trace=traces[Number(item.dataset.traceIndex)];item.querySelector('[type="checkbox"]').onchange=event=>{trace.visible=event.target.checked;drawTraces()};item.querySelector('[type="color"]').oninput=event=>{trace.color=event.target.value;drawTraces()};item.querySelector('[type="text"]').onchange=event=>{trace.name=event.target.value;drawTraces()};item.ondragstart=event=>event.dataTransfer.setData('text/plain',item.dataset.traceIndex);item.ondragover=event=>event.preventDefault();item.ondrop=event=>{event.preventDefault();const from=Number(event.dataTransfer.getData('text/plain')),to=Number(item.dataset.traceIndex);const [moved]=traces.splice(from,1);traces.splice(to,0,moved);renderTraceList();drawTraces()}})}
let chartZoom=1,chartPan=0,cursorMode=false,chartCursors=[],chartDomain=null,dragStart=null;
function drawTraces(){const svg=$('#chart'),metricName=$('#chartMetric').value,visible=traces.filter(trace=>trace.visible);const values=visible.flatMap(trace=>trace.points.map(point=>point[metricName]).filter(Number.isFinite));const allX=visible.flatMap(trace=>trace.points.map(point=>point.frequency_hz).filter(Number.isFinite));if(!values.length||!allX.length){svg.innerHTML='';return}const w=960,h=360,pad=52,min=Math.min(...values),max=Math.max(...values),range=Math.max(max-min,1),xmin=Math.min(...allX),xmax=Math.max(...allX);chartDomain={xmin,xmax};const x=value=>pad+(((value-xmin)/Math.max(xmax-xmin,1)-chartPan)*chartZoom)*(w-pad*2),y=value=>h-pad-(value-min)/range*(h-pad*2);let html='';for(let i=0;i<5;i++){const yy=pad+i*(h-pad*2)/4;html+=`<line class="grid-line" x1="${pad}" y1="${yy}" x2="${w-pad}" y2="${yy}"/><text class="axis-label" x="4" y="${yy+4}">${(max-i*range/4).toFixed(2)}</text>`}visible.forEach(trace=>{const segments=[];let current=[];trace.points.forEach(point=>{if(Number.isFinite(point[metricName])&&Number.isFinite(point.frequency_hz))current.push(point);else if(current.length){segments.push(current);current=[]}});if(current.length)segments.push(current);segments.forEach(segment=>{html+=`<polyline fill="none" stroke="${trace.color}" stroke-width="3" points="${segment.map(point=>`${x(point.frequency_hz)},${y(point[metricName])}`).join(' ')}"/>`});html+=trace.points.filter(point=>Number.isFinite(point[metricName])&&Number.isFinite(point.frequency_hz)).map(point=>`<circle cx="${x(point.frequency_hz)}" cy="${y(point[metricName])}" r="4" fill="var(--panel)" stroke="${trace.color}" stroke-width="3"><title>${escapeHtml(trace.name)} · ${(point.frequency_hz/1e6).toFixed(3)} MHz · ${point[metricName]}</title></circle>`).join('')});chartCursors.forEach(value=>{const xx=x(value);html+=`<line class="cursor-line" x1="${xx}" y1="${pad}" x2="${xx}" y2="${h-pad}"/>`});svg.innerHTML=html;$('#cursorDelta').textContent=chartCursors.length===2?`ΔF ${Math.abs(chartCursors[1]-chartCursors[0])/1e6} MHz`:'A/B: —'}
$('#chartMetric').onchange=drawTraces;$('#resetChart').onclick=()=>{chartZoom=1;chartPan=0;chartCursors=[];drawTraces()};$('#cursorToggle').onclick=()=>{cursorMode=!cursorMode;$('#cursorToggle').classList.toggle('active',cursorMode)};
$('#chart').addEventListener('wheel',event=>{event.preventDefault();chartZoom=Math.max(1,Math.min(10,chartZoom*(event.deltaY<0?1.25:.8)));chartPan=Math.max(0,Math.min(1-1/chartZoom,chartPan));drawTraces()},{passive:false});$('#chart').addEventListener('pointerdown',event=>{if(cursorMode&&chartDomain){const rect=event.currentTarget.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width));const normalized=chartPan+ratio/chartZoom;chartCursors.push(chartDomain.xmin+normalized*(chartDomain.xmax-chartDomain.xmin));chartCursors=chartCursors.slice(-2);drawTraces();return}dragStart={x:event.clientX,pan:chartPan};event.currentTarget.setPointerCapture(event.pointerId);event.currentTarget.classList.add('dragging')});$('#chart').addEventListener('pointermove',event=>{if(!dragStart||chartZoom<=1)return;const rect=event.currentTarget.getBoundingClientRect();chartPan=Math.max(0,Math.min(1-1/chartZoom,dragStart.pan-(event.clientX-dragStart.x)/rect.width/chartZoom));drawTraces()});$('#chart').addEventListener('pointerup',event=>{dragStart=null;event.currentTarget.classList.remove('dragging')});

async function loadRuns(){try{const response=await fetch('/api/runs',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load runs');allRuns=Array.isArray(data.runs)?data.runs:[];renderRuns()}catch(error){allRuns=[];$('#runsGrid').innerHTML=`<tr><td colspan="9">${escapeHtml(error.message)}</td></tr>`}}
function filteredRuns(){const query=$('#runSearch').value.trim().toLowerCase(),source=$('#runSource').value,status=$('#runStatus').value,sort=$('#runSort').value;const rows=allRuns.filter(run=>(!query||`${run.test_name} ${run.run_id}`.toLowerCase().includes(query))&&(source==='all'||(source==='demo')===run.simulated)&&(status==='all'||run.status.toLowerCase()===status));return rows.sort((a,b)=>sort==='oldest'?Date.parse(a.created_at)-Date.parse(b.created_at):sort==='name'?a.test_name.localeCompare(b.test_name):sort==='points'?b.completed_points-a.completed_points:Date.parse(b.created_at)-Date.parse(a.created_at))}
function renderRuns(){const rows=filteredRuns();$('#runsGrid').innerHTML=rows.map(run=>`<tr><td><input class="compare-check" type="checkbox" data-compare-key="${escapeHtml(run.run_key)}" ${selectedRunKeys.has(run.run_key)?'checked':''}></td><td>${run.created_at?new Date(run.created_at).toLocaleString():'—'}</td><td>${escapeHtml(run.test_name)}</td><td><code>${escapeHtml(run.run_id)}</code></td><td><span class="state-chip">${run.simulated?'DEMO':'HARDWARE'}</span></td><td>${escapeHtml(run.status)}</td><td>${run.completed_points}</td><td><code>output/${escapeHtml(run.run_key)}/</code></td><td><div class="row-actions"><button class="secondary-button" type="button" data-run-key="${escapeHtml(run.run_key)}">OPEN</button>${run.artifact_urls?.report?`<a class="secondary-button" href="${run.artifact_urls.report}" target="_blank" rel="noopener">REPORT</a>`:''}</div></td></tr>`).join('')||`<tr><td colspan="9">${language==='zh'?'沒有符合條件的紀錄':'No matching runs'}</td></tr>`;$('#runMobileCards').innerHTML=rows.map(run=>`<article class="run-row"><header><div><h3>${escapeHtml(run.test_name)}</h3><p>${new Date(run.created_at).toLocaleString()}</p></div><input class="compare-check" type="checkbox" data-compare-key="${escapeHtml(run.run_key)}" ${selectedRunKeys.has(run.run_key)?'checked':''}></header><code class="run-location">output/${escapeHtml(run.run_key)}/</code><button class="secondary-button" data-run-key="${escapeHtml(run.run_key)}">OPEN</button></article>`).join('');$('#compareRuns').disabled=selectedRunKeys.size<2||selectedRunKeys.size>8}
['runSearch','runSource','runStatus','runSort'].forEach(id=>$('#'+id).addEventListener(id==='runSearch'?'input':'change',renderRuns));
$('#refreshRuns').onclick=loadRuns;
let selectedRun=null;
async function openRunDetail(runKey){const response=await fetch(`/api/runs/${encodeURIComponent(runKey)}`);const record=await response.json();if(!response.ok)throw new Error(record.error||'Unable to load run');selectedRun={...record,runKey};const metadata=record.metadata||{};$('#dialogTitle').textContent=metadata.test_name||metadata.run_id||runKey;$('#dialogOutput').textContent=record.output_location;$('#dialogSummary').innerHTML=metric('TIME',metadata.created_at?new Date(metadata.created_at).toLocaleString():'—')+metric('STATUS',metadata.status||'—')+metric('RUN ID',metadata.run_id||'—');const urls=(await (await fetch('/api/runs')).json()).runs.find(run=>run.run_key===runKey)?.artifact_urls||{};$('#dialogArtifacts').innerHTML=Object.entries(urls).map(([key,url])=>`<a href="${url}" target="_blank" rel="noopener">${key.toUpperCase()}</a>`).join('');$('#dialogTechnical').textContent=JSON.stringify({metadata,results:record.results,raw_files:record.raw_files,waveform_reference:record.waveform_reference},null,2);$('#trashConfirmation').hidden=true;$('#trashRunId').value='';$('#runDialog').showModal()}
function handleRunGrid(event){const check=event.target.closest('[data-compare-key]');if(check){check.checked?selectedRunKeys.add(check.dataset.compareKey):selectedRunKeys.delete(check.dataset.compareKey);renderRuns();return}const button=event.target.closest('[data-run-key]');if(button)openRunDetail(button.dataset.runKey).catch(error=>toast(error.message))}
$('#runsGrid').onclick=handleRunGrid;$('#runMobileCards').onclick=handleRunGrid;
$('#compareRuns').onclick=async()=>{try{const palette=['#27dce6','#ffb84d','#a78bfa','#45d69a','#ff6374','#4da3ff','#f472b6','#94a3b8'];const records=await Promise.all([...selectedRunKeys].map(async key=>{const response=await fetch(`/api/runs/${encodeURIComponent(key)}`);const record=await response.json();if(!response.ok)throw new Error(record.error);return record}));traces=records.map((record,index)=>({id:record.metadata.run_id,name:record.metadata.test_name||record.metadata.run_id,color:palette[index],visible:true,points:normalizeStoredPoints(record.results)}));const bandwidths=new Set(traces.flatMap(trace=>trace.points.map(point=>point.bandwidth_hz).filter(Number.isFinite)));$('#emptyResults').hidden=true;$('#resultContent').hidden=false;$('#resultStatus').textContent='COMPARE';$('#resultTimestamp').textContent=new Date().toLocaleString();$('#resultRunId').textContent=traces.map(trace=>trace.id).join(', ');$('#resultOutput').textContent=language==='zh'?'多筆 Run 比較（原始檔案位置保持不變）':'Multi-run comparison (source locations unchanged)';$('#metrics').innerHTML=metric('RUNS',traces.length)+metric('POINTS',traces.reduce((sum,trace)=>sum+trace.points.length,0))+metric('BANDWIDTHS',bandwidths.size||'—')+metric('COMPATIBILITY',bandwidths.size<=1?'OK':'REVIEW');$('#artifactLinks').innerHTML='';renderTraceList();renderPointTable(traces[0]?.points||[]);drawTraces();if(bandwidths.size>1)$('#compareHint').textContent=language==='zh'?'警告：所選 Run 的頻寬不同，請勿直接做合規結論。':'Warning: selected runs use different bandwidths; do not infer compliance directly.';showView('results')}catch(error){toast(error.message)}};
$('#closeDialog').onclick=()=>$('#runDialog').close();
$('#openRunFolder').onclick=async()=>{if(!selectedRun)return;try{await post(`/api/runs/${encodeURIComponent(selectedRun.runKey)}/open-folder`,{});toast(language==='zh'?'已開啟輸出資料夾':'Output folder opened')}catch(error){toast(error.message)}};
$('#requestTrash').onclick=()=>{if(!selectedRun)return;const runId=String(selectedRun.metadata?.run_id||'');$('#trashConfirmation').hidden=false;$('#trashHelp').textContent=language==='zh'?`輸入 Run ID「${runId}」確認。資料會移至 output/.trash，可由管理者復原。`:`Type Run ID “${runId}” to confirm. Data moves to output/.trash and remains recoverable.`;$('#trashRunId').focus()};
$('#cancelTrash').onclick=()=>{$('#trashConfirmation').hidden=true;$('#trashRunId').value=''};
$('#trashRunId').oninput=()=>{$('#confirmTrash').disabled=!selectedRun||$('#trashRunId').value!==String(selectedRun.metadata?.run_id||'')};
$('#confirmTrash').onclick=async()=>{if(!selectedRun)return;try{
  // 刪除按鍵實際只移至可復原 .trash；後端還會再次核對 Run ID 與本機來源。
  await post(`/api/runs/${encodeURIComponent(selectedRun.runKey)}/trash`,{confirm_run_id:$('#trashRunId').value});$('#runDialog').close();await loadRuns();toast(language==='zh'?'紀錄已移至 Trash':'Run moved to Trash')
}catch(error){toast(error.message)}};
function calibrationExample(){return`frequency_hz,source_reference_dbm,receiver_reading_dbm
6085000000,-40.000,-40.850
6105000000,-40.000,-40.870
6125000000,-40.000,-40.900`}
$('#loadCalExample').onclick=()=>{$('#calReadings').value=calibrationExample();toast(language==='zh'?'已載入示範讀值；不可作為正式校正。':'Demo readings loaded; not valid for formal calibration.')};
$('#calculateCalibration').onclick=async()=>{try{const form=new FormData($('#calibrationForm')),lines=String(form.get('readings_csv')||'').trim().split(/\r?\n/).filter(Boolean),dataLines=lines[0]?.toLowerCase().includes('frequency_hz')?lines.slice(1):lines;const readings=dataLines.map((line,index)=>{const values=line.split(',').map(value=>Number(value.trim()));if(values.length!==3||values.some(value=>!Number.isFinite(value)))throw new Error(`CSV row ${index+1} is invalid`);return{frequency_hz:values[0],source_reference_dbm:values[1],receiver_reading_dbm:values[2]}});const payload={profile_id:form.get('profile_id'),route:form.get('route'),equipment_reference:form.get('equipment_reference'),calibrated_at:form.get('calibrated_at'),expires_at:form.get('expires_at'),readings};
  // 此按鍵只計算 Draft；後端仍禁止 Draft 套用到正式量測，避免示範線損成為合規資料。
  const result=await post('/api/calibration/draft-preview',payload);$('#calResult').hidden=false;$('#calLossTable').innerHTML=`<div class="metric-grid">${result.profile.points.map(point=>metric(`${(point.frequency_hz/1e6).toFixed(1)} MHz`,`${point.loss_db.toFixed(3)} dB`)).join('')}</div>`;$('#calProfileJson').textContent=JSON.stringify(result,null,2)
}catch(error){toast(error.message)}};
const today=new Date(),expiry=new Date(Date.now()+90*86400000);$('#calibrationForm [name="calibrated_at"]').value=today.toISOString().slice(0,10);$('#calibrationForm [name="expires_at"]').value=expiry.toISOString().slice(0,10);
function escapeHtml(value){const span=document.createElement('span');span.textContent=String(value);return span.innerHTML}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),3200)}
$('.copy-button').onclick=async()=>{try{await navigator.clipboard.writeText($('.command-card pre').innerText);toast(language==='zh'?'指令已複製':'Command copied')}catch{toast(language==='zh'?'請手動選取指令':'Select the command manually')}};
async function loadStatus(){try{const response=await fetch('/api/status');const status=await response.json();$('#serverState').textContent='ONLINE';if(status.hardware_enabled){$('#modeBadge').className='mode-badge hardware';$('#modeBadge b').textContent='HARDWARE';$('#instrumentState').textContent='RF ENABLED'}else{$('#instrumentState').textContent='VIEW ONLY'}}catch{$('#serverState').textContent='OFFLINE'}}
applyTheme(localStorage.getItem('cmp180-theme')||'dark');setAxis('single');applyLanguage();loadStatus();
